name: 'default_security'
description: 'default security check for agent outputs'
compliance:
  type: 'TOOL'
  name: 'default_compliance_tool'
desensitization:
  type: 'TOOL'
  name: 'default_mask_tool'
metadata:
  type: 'SECURITY'
  module: 'agentuniverse.agent.security.default.default_security'
  class: 'DefaultSecurity'