- type: markdown
  attributes:
    value: "Please add one of the following labels to the Labels option on the right before creating the PR: [feat]、[fix]、[docs]、[refactor]、[test]、[chore]. | 请在创建PR前，在右侧 Labels 选项中加上label的其中一个: [feat]、[fix]、[docs]、[refactor]、[test]、[chore]。"
- type: checkboxes
  attributes:
    label: PR check list
    description: When submitting a PR, please confirm the following points and put ☑️ in the boxes one by one. | 在提出pr时，请确认了以下几点，并逐一确认勾选。
    options:
      - label: I have read and understood the [contributor guidelines](https://github.com/antgroup/agentUniverse/blob/master/CONTRIBUTING.md). | 我已阅读并理解[贡献者指南](https://github.com/antgroup/agentUniverse/blob/master/CONTRIBUTING_zh.md)。
        required: true
      - label: I have checked for any duplicate features related to this request and communicated with the project maintainers. | 我已检查没有与此请求重复的功能并与项目维护者进行了沟通。
        required: true
      - label: I accept the suggestion of the maintainers to make changes to or close this PR. | 我接受此PR配合维护人员的建议进行修改或关闭。
        required: true
      - label: I have submitted the test files and can provide screenshots of the test results (required for feature or bug fixes) | 我已经提交了测试文件并可提供测试结果截图(功能修改、BUG修复类PR必须提供，其他按需)
        required: false
      - label: I have added or modified the documentation related to this PR | 我已经添加或修改了本次pr对应的文档说明(非必要，根据实际PR内容按需添加)
        required: false
      - label: I have added examples and notes if needed | 我已经添加了使用案例代码与文档说明(非必要，根据实际PR内容按需添加)
        required: false
- type: textarea
  attributes:
    label: details
    description: Please fill in the specific details of this PR.| 请详细填写本次PR的内容。
    value: |
      -
      -
      -
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: tests
    description: Please provide the path of test files and submit screenshots or files of the test results(fill in as needed). | 请填写测试文件路径并提供测试结果截图或文件(按需填写)。
    placeholder: "XXX func test file: ..."
  validations:
    required: false
- type: textarea
  attributes:
    label: tests
    description: Please list the names of the docs that were added or modified in this PR (fill in as needed). | 请列出本次PR新增或修改的文档名称(按需填写)。
    placeholder: "Add new docs: ..."
  validations:
    required: false