name: 💡 Question Report | 问题交流
description: Any questions you would like to discuss | 任何您想讨论的话题。
title: "💡 [Question] <your question xxx>"
labels: ["question"]
body:
- type: markdown
  attributes:
    value: "Please check whether there are any [issues](https://github.com/antgroup/agentUniverse/issues) or [documents](https://github.com/antgroup/agentUniverse/tree/master/docs/guidebook/en) that address your questions. | 搜索是否有[issues](https://github.com/antgroup/agentUniverse/issues) 或[文档](https://github.com/antgroup/agentUniverse/tree/master/docs/guidebook/zh) 提到了您的提问。"
- type: markdown
  attributes:
    value: "Please fill out the info before you submit a question | 请在您提交问题之前，填写以下信息。"
- type: textarea
  attributes:
    label: question
    description: Please describe in detail the question you would like to discuss. | 请详细描述您想讨论的问题
    placeholder: "My question is ..."
  validations:
    required: true
- type: markdown
  attributes:
    value: "If it involves the code, you can provide additional information as needed below. | 如果涉及agentUniverse代码您可以按需要补充如下信息。"
- type: textarea
  attributes:
    label: Version
    description: What is the version of your agentUniverse? | 您使用的agentUniverse版本是多少？
    placeholder: "Example: version 0.0.15"
  validations:
    required: false
- type: textarea
  attributes:
    label: System
    description: What is your system environment? | 您的系统版本是什么？ [Linux/Mac/Windows]
    placeholder: "Example: Ubuntu 20.04"
  validations:
    required: false
- type: textarea
  attributes:
    label: Actions
    description: What did you do? | 您做了什么操作？
    placeholder: "Describe the actions you took"
  validations:
    required: false
- type: textarea
  attributes:
    label: Problem
    description: What kind of problem are you having? | 您遇到了什么问题？
    placeholder: "Describe the problem"
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected
    description: What is your expected outcome? | 您期望的结果是怎样的？
    placeholder: "Describe the expected results"
  validations:
    required: false
- type: textarea
  attributes:
    label: reproduce
    description: Steps to reproduce the bug | bug复现步骤
    placeholder: "Step 1: ..., Step 2: ..."
  validations:
    required: false