name: 'train_dump_flow'
description: "train then dump instructions from dataset input"
nodes:
  - module: ''
    # upload sft dataset to training platform
    class: 'UploadNode'
    param_in_jsonl:
    param_out_jsonl: 'train_dump_flow.upload.out'
    datasets_in_jsonl:
      - 'none_flow.filter.out'
    dataset_out_jsonl:
    node_param:
      datagraph_token_name: 'dataflow token'
      dataset_name: 'dataagent_dataset'
      dataset_desc: 'dataagent dataset common'

  - module: ''
    # train sft model via sfs dataset
    class: 'TrainNode'
    param_in_jsonl: 'train_dump_flow.upload.out'
    param_out_jsonl: 'train_dump_flow.aci_train.out'
    datasets_in_jsonl:
    dataset_out_jsonl:

  - module: ''
    # pre deployed LLM infer service via artifact from train stage via platform with deploy func
    class: 'PreDeployNode'
    param_in_jsonl: 'train_dump_flow.aci_train.out'
    param_out_jsonl: 'train_dump_flow.aci_pre_deploy.out'
    datasets_in_jsonl:
    dataset_out_jsonl:

  - module: ''
    # dump answers from LLM inference service via prompts from platform
    class: 'DumpNode'
    param_in_jsonl: 'train_dump_flow.aci_pre_deploy.out'
    param_out_jsonl:
    datasets_in_jsonl:
      - 'dataset_build_flow.filter.out'
    dataset_out_jsonl: 'train_dump_flow.aci_dump.out'
    node_param:
      dump_lines: 100